/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agprogramlama_videogonderim;

import java.io.*;
import java.net.*;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author huseyinozkan
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtPort = new javax.swing.JTextField();
        btnGonderilecekVideo = new javax.swing.JButton();
        edtServerIP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtBilgi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBilgileriOnayla = new javax.swing.JButton();
        lblGonderilecekVideoSec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setBounds(new java.awt.Rectangle(300, 100, 800, 500));
        setResizable(false);

        edtPort.setText("5555");

        btnGonderilecekVideo.setText("Gönderilecek Video Seç");
        btnGonderilecekVideo.setEnabled(false);
        btnGonderilecekVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGonderilecekVideoActionPerformed(evt);
            }
        });

        edtServerIP.setText("127.0.0.1");

        jLabel4.setText("Bilgi");

        edtBilgi.setColumns(20);
        edtBilgi.setRows(5);
        edtBilgi.setEnabled(false);
        jScrollPane1.setViewportView(edtBilgi);

        jLabel3.setText("Port:");

        jLabel2.setText("Server IP:");

        btnBilgileriOnayla.setText("Bilgileri Onayla");
        btnBilgileriOnayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilgileriOnaylaActionPerformed(evt);
            }
        });

        lblGonderilecekVideoSec.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtServerIP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(edtPort)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnBilgileriOnayla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGonderilecekVideo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGonderilecekVideoSec)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBilgileriOnayla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGonderilecekVideo)
                    .addComponent(lblGonderilecekVideoSec))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGonderilecekVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGonderilecekVideoActionPerformed

        try {
            ButtonGonderilecekVideo_Click();
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGonderilecekVideoActionPerformed

    private void btnBilgileriOnaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilgileriOnaylaActionPerformed
        ButtonBilgileriOnayla_Click();
    }//GEN-LAST:event_btnBilgileriOnaylaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilgileriOnayla;
    private javax.swing.JButton btnGonderilecekVideo;
    private javax.swing.JTextArea edtBilgi;
    private javax.swing.JTextField edtPort;
    private javax.swing.JTextField edtServerIP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGonderilecekVideoSec;
    // End of variables declaration//GEN-END:variables

    private void ButtonGonderilecekVideo_Click() throws IOException {
        Client client = new Client();
        client.start();
    }

    private void ButtonBilgileriOnayla_Click() {
        edtServerIP.setEnabled(false);
        edtPort.setEnabled(false);
        btnBilgileriOnayla.setEnabled(false);
        btnGonderilecekVideo.setEnabled(true);
    }

    class Client extends Thread {

        @Override
        public void run() {
            String bilgi = "";

            try {
                ClientCommon.Host = edtServerIP.getText();
                ClientCommon.PortNumber = Integer.parseInt(edtPort.getText());

                Functions.DialogChooser();
                System.out.println("Path: " + ClientCommon.Path);
                System.out.println("Size: " + ClientCommon.KaynakBytes.length);
                ClientCommon.baslangic = 0;
                ClientCommon.bitis = ClientCommon.TamponBytes.length;
                lblGonderilecekVideoSec.setText(Functions.DosyaAdiniAl(ClientCommon.Path));
                btnGonderilecekVideo.setEnabled(false);

                // Text Area nın doldurulması
                bilgi = "Dosya Adı: " + Functions.DosyaAdiniAl(ClientCommon.Path) + "\n";
                bilgi += "Boyut: " + ClientCommon.KaynakBytes.length + " Bytes\n";
                bilgi += "Dosya Hazırlanıyor...\n";
                // Biti

                // Başlangıç İçin Veriler Gönderiliyor
                String sentence = "baslangic-" + Functions.DosyaAdiniAl(ClientCommon.Path) + "-" + ClientCommon.KaynakBytes.length;
                ClientCommon.sendData = sentence.getBytes();
                InetAddress IPAddress = InetAddress.getByName(ClientCommon.Host);
                DatagramPacket sendPacket = new DatagramPacket(ClientCommon.sendData, ClientCommon.sendData.length, IPAddress, ClientCommon.PortNumber);
                DatagramSocket clientSocket = new DatagramSocket();
                clientSocket.setSoTimeout(5000);
                clientSocket.send(sendPacket);
                int intSiraNo = 0;
                while (true) {
                    String strSiraNo = String.valueOf(intSiraNo);
                    ClientCommon.TamponBytes = Arrays.copyOfRange(ClientCommon.KaynakBytes, ClientCommon.baslangic, ClientCommon.bitis);

                    // Veriler Tampon Şeklinde Gönderiliyor
                    ClientCommon.sendData = ClientCommon.TamponBytes;
                    IPAddress = InetAddress.getByName(ClientCommon.Host);
                    sendPacket = new DatagramPacket(ClientCommon.sendData, ClientCommon.sendData.length, IPAddress, ClientCommon.PortNumber);
                    clientSocket = new DatagramSocket();
                    clientSocket.setSoTimeout(5000);
                    clientSocket.send(sendPacket);

                    if (ClientCommon.bitis > ClientCommon.KaynakBytes.length) {
                        break;
                    }

                    ClientCommon.baslangic = ClientCommon.bitis;
                    ClientCommon.bitis = ClientCommon.bitis + ClientCommon.TamponBytes.length;
                    
                    intSiraNo++;
                }

                // Bitiş İçin Veriler Gönderiliyor
                sentence = "bitis";
                ClientCommon.sendData = sentence.getBytes();
                IPAddress = InetAddress.getByName(ClientCommon.Host);
                sendPacket = new DatagramPacket(ClientCommon.sendData, ClientCommon.sendData.length, IPAddress, ClientCommon.PortNumber);
                clientSocket = new DatagramSocket();
                clientSocket.setSoTimeout(5000);
                clientSocket.send(sendPacket);

                // Text Area nın doldurulması
                bilgi += "Dosya Gönderme Başarılı\n\n";
                // Biti
            } catch (Exception ex) {
                bilgi += "Hata: " + ex.getMessage() + "\n";
                bilgi += "Dosya Gönderme Başarısız\n";
                bilgi += "Tekrar Deneyiniz\n\n";
                System.out.println(ex.getMessage());
            }

            btnGonderilecekVideo.setEnabled(true);
            edtBilgi.setText(bilgi + edtBilgi.getText());

        }

    }
}